"""Entorno válido de ejemplo: valores ficticios, ninguno real."""

import base64

VALID_ENV: dict[str, str] = {
    "APP_ENV": "development",
    "APP_BASE_URL": "http://localhost:8000",
    "WEB_BASE_URL": "http://localhost:3000",
    "COOKIE_DOMAIN": "localhost",
    "LOG_LEVEL": "info",
    "APP_TIMEZONE": "America/Argentina/Buenos_Aires",
    "DATABASE_URL": "postgresql+psycopg://app:clave-app@localhost:5432/brujula",
    "DATABASE_URL_MIGRATIONS": "postgresql+psycopg://migr:clave-migr@localhost:5432/brujula",
    "SESSION_SECRET": "s" * 40,
    "FIELD_ENCRYPTION_KEY": base64.urlsafe_b64encode(bytes(32)).decode(),
    "CSRF_SECRET": "c" * 40,
    "ADMIN_EMAILS": " Admin@Ejemplo.com , otra@ejemplo.com",
    "GOOGLE_CLIENT_ID": "google-client-id",
    "GOOGLE_CLIENT_SECRET": "google-client-secret",
    "GOOGLE_REDIRECT_URI": "http://localhost:8000/auth/google/callback",
    "GOOGLE_DISCOVERY_URL": "https://accounts.google.com/.well-known/openid-configuration",
    "SESSION_TTL_HOURS": "168",
    "RATE_LIMIT_AUTH_PER_MINUTE": "20",
    "RATE_LIMIT_UPLOAD_PER_HOUR": "10",
    "CSV_MAX_BYTES": "65536",
    "CSV_MAX_ROWS": "200",
    "LLM_EXTRACTION_MODEL": "modelo-extraccion",
    "LLM_CLASSIFICATION_MODEL": "modelo-clasificacion",
    "LLM_WRITER_MODEL": "modelo-redaccion",
    "LLM_EMBEDDING_MODEL": "modelo-embeddings",
    "LLM_EMBEDDING_DIMENSIONS": "1536",
    "LLM_JUDGE_MODEL": "modelo-juez",
    "ANTHROPIC_API_KEY": "anthropic-key",
    "OPENAI_API_KEY": "openai-key",
    "LLM_MONTHLY_BUDGET_USD": "50",
    "LANGFUSE_PUBLIC_KEY": "pk-test",
    "LANGFUSE_SECRET_KEY": "sk-test",
    "LANGFUSE_HOST": "https://cloud.langfuse.com",
    "SEC_USER_AGENT": "Brujula contacto@ejemplo.com",
    "BYMA_OPEN_DATA_BASE_URL": "https://byma.example.invalid",
    "DATA912_BASE_URL": "https://data912.example.invalid",
    "PRICE_DIVERGENCE_THRESHOLD_PCT": "2.5",
    "CRON_PRICES_DAILY": "0 19 * * 1-5",
    "CRON_FILINGS_CHECK": "0 */6 * * *",
    "CRON_NEWS_INGEST": "*/30 * * * *",
    "CRON_WEEKLY_DIGEST": "0 8 * * 6",
    "RESEND_API_KEY": "resend-key",
    "EMAIL_FROM": "Brujula <hola@ejemplo.com>",
    "RESEND_WEBHOOK_SECRET": "resend-webhook-secret",
    "PRICE_PRO_ARS": "9999.99",
    "FREE_PLAN_MAX_POSITIONS": "5",
    "FREE_PLAN_DIGESTS_PER_MONTH": "1",
    "FOUNDER_PLAN_OPEN": "true",
    "DOCUMENT_STORAGE_DIR": "./data/documents",
    "CONFIG_DIR": "./config",
    "PROMPTS_DIR": "./prompts",
}
